const List<Map<String, String>> usuarios = [
  {
    'nombre': 'Juan Pérez',
    'userImagen': 'https://randomuser.me/api/portraits/men/1.jpg',
    'estado': 'Activo',
    'profesion': 'Ingeniero',
    'correoElectronico': 'juan.perez@example.com',
  },
  {
    'nombre': 'María García',
    'userImagen': 'https://randomuser.me/api/portraits/women/1.jpg',
    'estado': 'Inactivo',
    'profesion': 'Doctora',
    'correoElectronico': 'maria.garcia@example.com',
  },
  {
    'nombre': 'Carlos López',
    'userImagen': 'https://randomuser.me/api/portraits/men/2.jpg',
    'estado': 'Activo',
    'profesion': 'Abogado',
    'correoElectronico': 'carlos.lopez@example.com',
  },
  {
    'nombre': 'José González',
    'userImagen': 'https://randomuser.me/api/portraits/men/4.jpg',
    'estado': 'Activo',
    'profesion': 'Contador',
    'correoElectronico': 'jose.gonzalez@example.com',
  },
  {
    'nombre': 'Marta Sánchez',
    'userImagen': 'https://randomuser.me/api/portraits/women/4.jpg',
    'estado': 'Inactivo',
    'profesion': 'Psicóloga',
    'correoElectronico': 'marta.sanchez@example.com',
  },
  {
    'nombre': 'David Ramírez',
    'userImagen': 'https://randomuser.me/api/portraits/men/5.jpg',
    'estado': 'Activo',
    'profesion': 'Desarrollador',
    'correoElectronico': 'david.ramirez@example.com',
  },
  {
    'nombre': 'Sara Torres',
    'userImagen': 'https://randomuser.me/api/portraits/women/5.jpg',
    'estado': 'Inactivo',
    'profesion': 'Diseñadora',
    'correoElectronico': 'sara.torres@example.com',
  },
  {
    'nombre': 'Jorge Díaz',
    'userImagen': 'https://randomuser.me/api/portraits/men/6.jpg',
    'estado': 'Activo',
    'profesion': 'Analista',
    'correoElectronico': 'jorge.diaz@example.com',
  },
  {
    'nombre': 'Elena Ruiz',
    'userImagen': 'https://randomuser.me/api/portraits/women/6.jpg',
    'estado': 'Inactivo',
    'profesion': 'Investigadora',
    'correoElectronico': 'elena.ruiz@example.com',
  },
  {
    'nombre': 'Pedro Morales',
    'userImagen': 'https://randomuser.me/api/portraits/men/7.jpg',
    'estado': 'Activo',
    'profesion': 'Gerente',
    'correoElectronico': 'pedro.morales@example.com',
  },
  {
    'nombre': 'Isabel Ortiz',
    'userImagen': 'https://randomuser.me/api/portraits/women/7.jpg',
    'estado': 'Inactivo',
    'profesion': 'Consultora',
    'correoElectronico': 'isabel.ortiz@example.com',
  },
  {
    'nombre': 'Ricardo Castro',
    'userImagen': 'https://randomuser.me/api/portraits/men/8.jpg',
    'estado': 'Activo',
    'profesion': 'Administrador',
    'correoElectronico': 'ricardo.castro@example.com',
  },
];